server:
  #服务端口
  port: 10012
spring:
  application:
    name: circuitbreaker-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:9001
          predicates:
            - Path=/nacos/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#            - name: CircuitBreakerStatePrinter
          filters:
            - name: CircuitBreakerStatePrinter
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
#                fallbackUri: forward:/myfallback