server:
  #服务端口
  port: 10015
spring:
  application:
    name: gateway-dynamic-route
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:9001
          predicates:
            - Path=/nacos/**
          filters:
            - name: BizLogicRoute
              args:
                prodEnvUri: http://localhost:9001
                testEnvUri: http://localhost:9003
