server:
  #服务端口
  port: 10013

spring:
  application:
    name: circuitbreaker-gateway
  # redis配置
  redis:
    host: localhost
    port: 6379
  cloud:
    # 忽略虚拟机网卡，避免提示o.s.cloud.commons.util.InetUtils : Cannot determine local hostname
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:9001
          predicates:
            - Path=/nacos/**
          filters:
            - name: RequestRateLimiter
              args:
                # 令牌入桶的速度为每秒10个，相当于QPS
                redis-rate-limiter.replenishRate: 10
                # 桶内能装20个令牌，相当于峰值，要注意的是：第一秒从桶内能去20个，但是第二秒只能取到10个了，因为入桶速度是每秒10个
                redis-rate-limiter.burstCapacity: 20
                # 每个请求需要的令牌数
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@userKeyResolver}"
