server:
  port: 10009

spring:
  application:
    name: gateway-by-loadbalance
  cloud:
    nacos:
      # 注册中心的配置
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: path_route_lb
          uri: lb://nacos-provider
          predicates:
            - Path=/nacos/**
